name: Create UAT PR

on:
  pull_request:
    branches:
      - develop  # Trigger workflow when a PR is merged into 'develop'

jobs:
  create-pr-uat:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract the branch name from the PR event
      - name: Get the feature branch name
        id: get_feature_branch
        run: |
          feature_branch=$(echo "${{ github.event.pull_request.head.ref }}")
          echo "Feature branch: $feature_branch"
          echo "::set-output name=feature_branch::$feature_branch"

      # Step 2: Create PR for UAT
      - name: Create PR for UAT
        run: |
          feature_branch=${{ steps.get_feature_branch.outputs.feature_branch }}
          pr_title="${feature_branch}-uat"
          pr_body="PR for feature merge from $feature_branch to uat"
          echo "Creating PR for branch: $feature_branch"
          gh pr create --base uat --head $feature_branch --title "$pr_title" --body "$pr_body"
        env:
          GH_TOKEN: ${{ secrets.GT_TOKEN }}
